# Changes here will be overwritten by Copier
_commit: v2.0.1
_src_path: gh:lincc-frameworks/python-project-template
author_email: edonoso@conicet.gov.ar
author_name: Emilio Donoso
create_example_module: false
custom_install: true
enforce_style:
- ruff_lint
- ruff_format
failure_notification: []
include_benchmarks: false
include_docs: true
include_notebooks: true
mypy_type_checking: none
package_name: gundam
project_license: none
project_name: gundam
project_organization: lincc-frameworks-mask-incubator
python_versions:
- '3.9'
- '3.10'
- '3.11'
