# ==============================================================
# CI with GitHub Actions
# ==============================================================

name: gundam CI

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@master
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version}}
      - name: Install pandoc
        run: sudo apt install pandoc
      - name: Install MPI
        run: sudo apt -y install mpi mpich
      - name: Install tox
        run: pip install tox tox-gh-actions
      - name: Test with tox
        run: tox -r 
